# Generated by Django 4.2.2 on 2023-06-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talabaty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('profile_image', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('shop', 'Shop'), ('customer', 'Customer'), ('rider', 'Rider')], max_length=10),
        ),
    ]
