# Generated by Django 4.2.2 on 2023-06-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talabaty', '0002_userprofile_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
