# Generated by Django 4.2.2 on 2023-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talabaty', '0003_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(max_length=255, null=True, upload_to='profile_images/'),
        ),
    ]
