# Generated by Django 4.2.2 on 2023-06-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talabaty', '0005_userprofile_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
