# Generated by Django 4.2.2 on 2023-06-18 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talabaty', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=255)),
                ('discount_price', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('slug', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('profile_images', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='talabaty.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
